import { Injectable } from '@angular/core';
import { Pais } from './Pais';

@Injectable({
  providedIn: 'root',
})
export class PaisService {
  readonly baseUrl = '../assets/cidades/';

  protected PaisList: Pais[] = [
    {
      id: 0,
      pais: 'Portugal',
      paisurl: 'portugal',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/lisboa.png`,
      fotocard: `${this.baseUrl}/card/lisboa.png`,
      cidade: 'Lisboa',
      custodevida: 'R$5.400 - R$9.900',
      temperatura: 'Média anual de 17°C',
      lingua: 'Português',
      internet: '40 Mbps',
      descricao:
        'Portugal é um destino inspirador. Com sua rica história, cidades pitorescas e belas paisagens, o país oferece um ambiente inspirador para trabalhar e explorar. Lisboa, a capital, combina tradição e modernidade, com bairros históricos, como Alfama, e uma cena tecnológica em crescimento no Parque das Nações. O Porto, conhecido por suas vinícolas e charme urbano, também atrai nômades digitais em busca de uma atmosfera acolhedora.',
    },
    {
      id: 1,
      pais: 'Tailândia',
      paisurl: 'tailandia',
      regiao: 'Sudeste Asiático',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/bangkok.png`,
      fotocard: `${this.baseUrl}/card/bangkok.png`,
      cidade: 'Bangkok',
      custodevida: 'R$3.000 - R$7.000',
      temperatura: 'Média anual de 28°C',
      lingua: 'Tailandês',
      internet: '25 Mbps',
      descricao:
        'A Tailândia é um paraíso exótico e vibrante, oferecendo uma fusão única entre praias deslumbrantes, selvas exuberantes e cidades movimentadas. Com uma combinação de infraestrutura moderna e cultura tradicional, é um local atraente para trabalhar remotamente. Bangkok, a capital, é um hub dinâmico com uma cena de coworking em crescimento, enquanto destinos como Chiang Mai e as ilhas tailandesas proporcionam uma mistura perfeita de beleza natural, gastronomia deliciosa e opções de lazer.',
    },
    {
      id: 2,
      pais: 'Costa Rica',
      paisurl: 'costa-rica',
      regiao: 'América Central',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/san-jose.png`,
      fotocard: `${this.baseUrl}/card/san-jose.png`,
      cidade: 'San Jose',
      custodevida: 'R$4.500 - R$8.000',
      temperatura: 'Média anual de 27°C',
      lingua: 'Espanhol',
      internet: '10 Mbps',
      descricao:
        'A Costa Rica é um refúgio tropical fascinante para nômades digitais, oferecendo uma harmoniosa conexão entre natureza exuberante e comodidades modernas. Com suas praias deslumbrantes, florestas tropicais biodiversas e parques nacionais bem preservados, o país proporciona um ambiente inspirador para trabalhar remotamente. Cidades como San José oferecem variedade de atividades ao ar livre, como surf, trilhas e observação de vida selvagem.',
    },
    {
      id: 3,
      pais: 'México',
      paisurl: 'mexico',
      regiao: 'América do Norte',
      tempovisa: '7 dias',
      fotofull: `${this.baseUrl}/full/playa-del-carmen.png`,
      fotocard: `${this.baseUrl}/card/playa-del-carmen.png`,
      cidade: 'Playa del Carmen',
      custodevida: 'R$3.600 - R$6.500',
      temperatura: 'Média anual de 27°C',
      lingua: 'Espanhol',
      internet: '20 Mbps',
      descricao:
        'O México é um destino vibrante e diversificado para nômades digitais, oferecendo uma fusão rica entre cultura, história e paisagens deslumbrantes. Cidades como Cidade do México e Playa del Carmen oferecem uma mistura emocionante de vida urbana e praias cativantes. A gastronomia mexicana é renomada, proporcionando uma experiência culinária única. As ruínas antigas, como as de Chichen Itza, e as belas praias da Riviera Maya adicionam um toque de aventura e exploração à vida de nômade digital no México.',
    },
    {
      id: 4,
      pais: 'Malásia',
      paisurl: 'malasia',
      regiao: 'Sudeste Asiático',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/kuala-lumpur.png`,
      fotocard: `${this.baseUrl}/card/kuala-lumpur.png`,
      cidade: 'Kuala Lumpur',
      custodevida: 'R$3.000 - R$5.500',
      temperatura: 'Média anual de 27°C',
      lingua: 'Malaio',
      internet: '20 Mbps',
      descricao:
        'A Malásia é um destino intrigante, combinando uma mistura fascinante de culturas, paisagens variadas e uma infraestrutura moderna. Kuala Lumpur, a capital, oferece uma atmosfera cosmopolita com arranha-céus impressionantes e uma cena de coworking em crescimento. Além disso, cidades como Penang e Langkawi proporcionam um ambiente mais descontraído, com belas praias e uma vibração cultural única. A rica culinária malasiana é uma atração por si só, refletindo a diversidade étnica do país.',
    },
    {
      id: 5,
      pais: 'Estônia',
      paisurl: 'estonia',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/tallinn.png`,
      fotocard: `${this.baseUrl}/card/tallinn.png`,
      cidade: 'Tallinn',
      custodevida: 'R$4.500 - R$7.500',
      temperatura: 'Média anual de 7°C',
      lingua: 'Estoniano',
      internet: '70 Mbps',
      descricao:
        'A Estônia é um destino encantador, com uma mistura única de inovação digital e beleza natural. A capital, Tallinn, oferece uma combinação de história medieval e infraestrutura moderna, incluindo zonas de Wi-Fi gratuito em toda a cidade. O programa de cidadania eletrônica da Estônia permite aos nômades digitais estabelecer uma presença legal e acessar serviços online de forma conveniente.',
    },
    {
      id: 6,
      pais: 'Irlanda',
      paisurl: 'irlanda',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/dublin.png`,
      fotocard: `${this.baseUrl}/card/dublin.png`,
      cidade: 'Dublin',
      custodevida: 'R$9.900 - R$13.500',
      temperatura: 'Média anual de 10°C',
      lingua: 'Inglês',
      internet: '75 Mbps',
      descricao:
        'A Irlanda é um destino cativante para nômades digitais, oferecendo uma combinação única de charme histórico, paisagens deslumbrantes e uma atmosfera acolhedora. Cidades como Dublin, com sua cena tecnológica em crescimento, proporcionam uma infraestrutura moderna para trabalhar remotamente. A cultura rica, a música tradicional e os pubs animados acrescentam um toque especial à experiência de nômade digital na Irlanda, proporcionando um equilíbrio atraente entre trabalho e lazer.',
    },
    {
      id: 7,
      pais: 'Argentina',
      paisurl: 'argentina',
      regiao: 'América do Sul',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/buenos-aires.png`,
      fotocard: `${this.baseUrl}/card/buenos-aires.png`,
      cidade: 'Buenos Aires',
      custodevida: 'R$2.700 - R$5.000',
      temperatura: 'Média anual de 18°C',
      lingua: 'Espanhol',
      internet: '25 Mbps',
      descricao:
        'A Argentina é um destino apaixonante para nômades digitais, com uma mistura envolvente de cultura, história e vastidão geográfica. Buenos Aires, a capital, oferece uma atmosfera artística e animada, além de uma crescente cena de coworking e tecnologia. A rica cultura argentina é refletida na dança do tango, na culinária famosa por seus bifes e na paixão pelo futebol.',
    },
    {
      id: 8,
      pais: 'Vietnã',
      paisurl: 'vietna',
      regiao: 'Sudeste Asiático',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/ho-chi-minh.png`,
      fotocard: `${this.baseUrl}/card/ho-chi-minh.png`,
      cidade: 'Ho Chi Minh',
      custodevida: 'R$2.500 - R$4.500',
      temperatura: 'Média anual de 28°C',
      lingua: 'Vietnamita',
      internet: '25 Mbps',
      descricao:
        'O Vietnã é um país exótico que oferece uma fusão intrigante de história rica, culinária deliciosa e paisagens diversas. Ho Chi Minh, a maior cidade do país, possui uma mistura de cultura tradicional e modernidade, com uma cena crescente de coworking. As belezas naturais do Vietnã vão desde as praias deslumbrantes de Da Nang até as montanhas de Sapa. A comida vietnamita é renomada internacionalmente, oferecendo uma experiência gastronômica única.',
    },
    {
      id: 9,
      pais: 'Espanha',
      paisurl: 'espanha',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/barcelona.png`,
      fotocard: `${this.baseUrl}/card/barcelona.png`,
      cidade: 'Barcelona',
      custodevida: 'R$7.200 - R$10.500',
      temperatura: 'Média anual de 17°C',
      lingua: 'Espanhol',
      internet: '50 Mbps',
      descricao:
        'A Espanha é um país cativante, conhecido por sua cultura vibrante, praias deslumbrantes e cidades históricas. Barcelona, uma das cidades mais famosas da Espanha, oferece uma mistura única de arquitetura modernista e estilo de vida descontraído. Com uma cena de coworking em crescimento e uma rica herança cultural, a cidade proporciona um ambiente inspirador para nômades digitais.',
    },
    {
      id: 10,
      pais: 'Indonésia',
      paisurl: 'indonesia',
      regiao: 'Sudeste Asiático',
      tempovisa: '30 dias (visa on arrival)',
      fotofull: `${this.baseUrl}/full/bali.png`,
      fotocard: `${this.baseUrl}/card/bali.png`,
      cidade: 'Bali',
      custodevida: 'R$2.800 - R$5.500',
      temperatura: 'Média anual de 26°C',
      lingua: 'Indonésio',
      internet: '20 Mbps',
      descricao:
        'A Indonésia é um paraíso tropical atraente para nômades digitais em busca de beleza natural e espiritualidade. Bali, conhecida por suas praias exuberantes e atmosfera relaxante, é um destino popular entre os nômades digitais. Com uma cena de coworking vibrante e retiros espirituais, Bali oferece um ambiente propício para trabalho e relaxamento. Além disso, a rica cultura balinesa, as atividades ao ar livre, como surfe e yoga, e os templos majestosos acrescentam uma dimensão única à experiência de nômade digital.',
    },
    {
      id: 11,
      pais: 'Canadá',
      paisurl: 'canada',
      regiao: 'América do Norte',
      tempovisa: 'Exige visto',
      fotofull: `${this.baseUrl}/full/vancouver.png`,
      fotocard: `${this.baseUrl}/card/vancouver.png`,
      cidade: 'Vancouver',
      custodevida: 'R$8.000 - R$13.000',
      temperatura: 'Média anual de 10°C',
      lingua: 'Inglês e Francês',
      internet: '100 Mbps',
      descricao:
        'O Canadá oferece um ambiente acolhedor para nômades digitais que desejam explorar vastas paisagens e cidades modernas. Vancouver, situada entre o oceano e as montanhas, é uma cidade cosmopolita com uma cena de tecnologia em crescimento. A beleza natural da região oferece oportunidades para atividades ao ar livre. Além disso, o Canadá é conhecido por sua qualidade de vida, educação de qualidade e diversidade cultural.',
    },
    {
      id: 12,
      pais: 'Grécia',
      paisurl: 'grecia',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/atenas.png`,
      fotocard: `${this.baseUrl}/card/atenas.png`,
      cidade: 'Atenas',
      custodevida: 'R$5.600 - R$9.800',
      temperatura: 'Média anual de 18°C',
      lingua: 'Grego',
      internet: '35 Mbps',
      descricao:
        'A Grécia oferece uma mistura encantadora de história antiga, praias deslumbrantes e uma atmosfera relaxada. Atenas, a capital, é uma cidade rica em cultura e história, com sítios arqueológicos icônicos, como a Acrópole. Com uma cena emergente de tecnologia e espaços de coworking, a Grécia oferece oportunidades para nômades digitais. As ilhas gregas, com suas águas cristalinas e charme pitoresco, proporcionam um refúgio tranquilo para relaxamento e inspiração.',
    },
    {
      id: 13,
      pais: 'Austrália',
      paisurl: 'australia',
      regiao: 'Oceania',
      tempovisa: '3 meses (eVisitor)',
      fotofull: `${this.baseUrl}/full/sydney.png`,
      fotocard: `${this.baseUrl}/card/sydney.png`,
      cidade: 'Sydney',
      custodevida: 'R$10.000 - R$16.000',
      temperatura: 'Média anual de 20°C',
      lingua: 'Inglês',
      internet: '50 Mbps',
      descricao:
        'A Austrália oferece uma combinação única de vida urbana moderna e belezas naturais impressionantes. Sydney, com seu famoso porto e estilo de vida descontraído, é uma cidade atraente para nômades digitais. Com uma economia forte e uma cena de tecnologia em crescimento, a Austrália oferece oportunidades de trabalho e exploração. Além disso, as vastas paisagens, como a Grande Barreira de Coral e as montanhas azuis, proporcionam aventuras emocionantes para quem procura um equilíbrio entre trabalho e lazer.',
    },
    {
      id: 14,
      pais: 'Japão',
      paisurl: 'japao',
      regiao: 'Ásia',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/toquio.png`,
      fotocard: `${this.baseUrl}/card/toquio.png`,
      cidade: 'Tóquio',
      custodevida: 'R$9.500 - R$15.000',
      temperatura: 'Média anual de 15°C',
      lingua: 'Japonês',
      internet: '100 Mbps',
      descricao:
        'O Japão oferece uma experiência única de modernidade e tradição, tornando-o um destino intrigante para nômades digitais. Tóquio, a capital, é uma metrópole futurista, conhecida por sua tecnologia de ponta e cultura pop. A cidade oferece uma cena de coworking em crescimento e oportunidades de exploração cultural. Além disso, as cidades históricas, como Quioto, e as belas paisagens naturais, como o Monte Fuji, enriquecem a experiência de viver no Japão.',
    },
    {
      id: 15,
      pais: 'Colômbia',
      paisurl: 'colombia',
      regiao: 'América do Sul',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/medellin.png`,
      fotocard: `${this.baseUrl}/card/medellin.png`,
      cidade: 'Medellín',
      custodevida: 'R$3.000 - R$6.000',
      temperatura: 'Média anual de 24°C',
      lingua: 'Espanhol',
      internet: '20 Mbps',
      descricao:
        'A Colômbia é um país fascinante com uma mistura única de cidades modernas e paisagens diversas. Medellín, conhecida por sua transformação urbana e , é uma cidade popular entre nômades digitais. Com uma cena de tecnologia em ascensão e uma vibração cultural vibrante, a Colômbia oferece um ambiente inspirador para trabalhar e explorar. Além disso, as belezas naturais, como a região do café e as praias caribenhas, proporcionam uma ampla gama de experiências.',
    },
    {
      id: 16,
      pais: 'Nova Zelândia',
      paisurl: 'nova-zelandia',
      regiao: 'Oceania',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/auckland.png`,
      fotocard: `${this.baseUrl}/card/auckland.png`,
      cidade: 'Auckland',
      custodevida: 'R$9.000 - R$14.000',
      temperatura: 'Média anual de 15°C',
      lingua: 'Inglês',
      internet: '70 Mbps',
      descricao:
        'A Nova Zelândia oferece uma paisagem deslumbrante e uma atmosfera relaxante, tornando-se um destino atraente para nômades digitais. Auckland, a maior cidade do país, oferece uma combinação de vida urbana e proximidade com a natureza. Com uma economia forte e uma cultura descontraída, a Nova Zelândia é um local propício para trabalho e qualidade de vida. As atividades ao ar livre, como trilhas, esportes aquáticos e observação de vida selvagem, são abundantes neste belo país insular.',
    },
    {
      id: 17,
      pais: 'Suíça',
      paisurl: 'suica',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/zurique.png`,
      fotocard: `${this.baseUrl}/card/zurique.png`,
      cidade: 'Zurique',
      custodevida: 'R$13.000 - R$20.000',
      temperatura: 'Média anual de 11°C',
      lingua: 'Alemão, Francês, Italiano',
      internet: '70 Mbps',
      descricao:
        'A Suíça é conhecida por sua qualidade de vida, paisagens montanhosas e cidades encantadoras. Zurique, a maior cidade do país, oferece uma mistura de inovação financeira e cultura rica. Com uma excelente infraestrutura e ambiente seguro, a Suíça é um destino atraente para nômades digitais. As atividades ao ar livre, como esqui nos Alpes, caminhadas e passeios de barco nos lagos, proporcionam uma combinação perfeita entre trabalho e lazer.',
    },
    {
      id: 18,
      pais: 'Noruega',
      paisurl: 'noruega',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/oslo.png`,
      fotocard: `${this.baseUrl}/card/oslo.png`,
      cidade: 'Oslo',
      custodevida: 'R$12.000 - R$18.000',
      temperatura: 'Média anual de 7°C',
      lingua: 'Norueguês',
      internet: '70 Mbps',
      descricao:
        'A Noruega é um país escandinavo conhecido por suas paisagens deslumbrantes, qualidade de vida e cultura nórdica. Oslo, a capital, combina modernidade e tradição em um ambiente encantador. Com uma forte economia e uma abordagem voltada para o bem-estar, a Noruega oferece oportunidades para nômades digitais que buscam equilíbrio entre trabalho e natureza. A exploração de fiordes, trilhas e as luzes do norte são algumas das experiências únicas que este país oferece.',
    },
    {
      id: 19,
      pais: 'Turquia',
      paisurl: 'turquia',
      regiao: 'Ásia/Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/istambul.png`,
      fotocard: `${this.baseUrl}/card/istambul.png`,
      cidade: 'Istambul',
      custodevida: 'R$3.500 - R$7.000',
      temperatura: 'Média anual de 14°C',
      lingua: 'Turco',
      internet: '20 Mbps',
      descricao:
        'A Turquia oferece uma rica combinação de história, cultura e paisagens diversificadas. Istambul, uma cidade que se estende entre a Ásia e a Europa, é um centro cultural e comercial vibrante. Com uma mistura de tradição e modernidade, a Turquia é um destino intrigante para nômades digitais. A culinária turca, os bazares históricos e os locais antigos, como a Hagia Sophia, tornam este país único e cativante.',
    },
    {
      id: 20,
      pais: 'Chile',
      paisurl: 'chile',
      regiao: 'América do Sul',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/santiago.png`,
      fotocard: `${this.baseUrl}/card/santiago.png`,
      cidade: 'Santiago',
      custodevida: 'R$3.800 - R$7.500',
      temperatura: 'Média anual de 14°C',
      lingua: 'Espanhol',
      internet: '30 Mbps',
      descricao:
        'O Chile oferece uma diversidade incrível de paisagens, desde desertos até montanhas e praias. Santiago, a capital, é uma cidade moderna com um cenário cultural e gastronômico em ascensão. Com uma economia estável e uma atmosfera acolhedora, o Chile é uma ótima opção para nômades digitais que desejam explorar a América do Sul.',
    },
    {
      id: 21,
      pais: 'Itália',
      paisurl: 'italia',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/roma.png`,
      fotocard: `${this.baseUrl}/card/roma.png`,
      cidade: 'Roma',
      custodevida: 'R$7.000 - R$12.000',
      temperatura: 'Média anual de 15°C',
      lingua: 'Italiano',
      internet: '50 Mbps',
      descricao:
        'A Itália é conhecida por sua rica história, arquitetura magnífica e culinária deliciosa. Roma, a capital, é um tesouro de arte e cultura, com locais icônicos como o Coliseu e o Vaticano. Além disso, cidades como Florença e Veneza oferecem experiências únicas. Com uma atmosfera encantadora e uma cena de café vibrante, a Itália é um destino atraente para nômades digitais.',
    },
    {
      id: 22,
      pais: 'Coreia do Sul',
      paisurl: 'coreia-do-sul',
      regiao: 'Ásia',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/seul.png`,
      fotocard: `${this.baseUrl}/card/seul.png`,
      cidade: 'Seul',
      custodevida: 'R$6.000 - R$11.000',
      temperatura: 'Média anual de 13°C',
      lingua: 'Coreano',
      internet: '100 Mbps',
      descricao:
        'A Coreia do Sul é um país conhecido por sua tecnologia avançada, cultura pop e paisagens diversificadas. Seul, a capital, oferece uma combinação de modernidade e tradição, com arranha-céus futuristas e palácios antigos. A cena de tecnologia e entretenimento é vibrante, tornando a Coreia do Sul uma opção intrigante para nômades digitais que buscam inovação e cultura.',
    },
    {
      id: 23,
      pais: 'Peru',
      paisurl: 'peru',
      regiao: 'América do Sul',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/lima.png`,
      fotocard: `${this.baseUrl}/card/lima.png`,
      cidade: 'Lima',
      custodevida: 'R$3.500 - R$7.000',
      temperatura: 'Média anual de 19°C',
      lingua: 'Espanhol',
      internet: '20 Mbps',
      descricao:
        'O Peru é um país repleto de história antiga, paisagens espetaculares e culinária renomada. Lima, a capital, combina tradição e modernidade, com uma cena gastronômica em crescimento e locais históricos como Machu Picchu. Com uma atmosfera acolhedora e uma rica herança cultural, o Peru oferece uma experiência autêntica para nômades digitais que desejam explorar as maravilhas da América do Sul.',
    },
    {
      id: 24,
      pais: 'Áustria',
      paisurl: 'austria',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/viena.png`,
      fotocard: `${this.baseUrl}/card/viena.png`,
      cidade: 'Viena',
      custodevida: 'R$8.000 - R$13.000',
      temperatura: 'Média anual de 11°C',
      lingua: 'Alemão',
      internet: '50 Mbps',
      descricao:
        'A Áustria é um país europeu conhecido por sua rica história, música clássica e cenários deslumbrantes. Viena, a capital, oferece uma mistura de arquitetura imperial e inovação moderna. Com uma alta qualidade de vida, cafés charmosos e uma cena artística vibrante, a Áustria é um local atraente para nômades digitais que buscam inspiração e cultura.',
    },
    {
      id: 25,
      pais: 'Singapura',
      paisurl: 'singapura',
      regiao: 'Sudeste Asiático',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/singapura.png`,
      fotocard: `${this.baseUrl}/card/singapura.png`,
      cidade: 'Singapura',
      custodevida: 'R$9.000 - R$15.000',
      temperatura: 'Média anual de 27°C',
      lingua: 'Inglês, Malaio, Chinês, Tâmil',
      internet: '80 Mbps',
      descricao:
        'Singapura é uma cidade-estado moderna e cosmopolita, conhecida por sua eficiência, diversidade cultural e arquitetura futurista. Com uma economia forte e uma infraestrutura avançada, Singapura é um centro financeiro e tecnológico que também oferece uma alta qualidade de vida. A fusão de culturas, as opções de gastronomia e os parques urbanos fazem de Singapura um local atrativo para nômades digitais.',
    },
    {
      id: 26,
      pais: 'Croácia',
      paisurl: 'croacia',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/dubrovnik.png`,
      fotocard: `${this.baseUrl}/card/dubrovnik.png`,
      cidade: 'Dubrovnik',
      custodevida: 'R$5.000 - R$9.000',
      temperatura: 'Média anual de 16°C',
      lingua: 'Croata',
      internet: '40 Mbps',
      descricao:
        'A Croácia é um país com uma costa deslumbrante no Mar Adriático e uma rica história. Dubrovnik, conhecida como a "Pérola do Adriático", é uma cidade medieval cercada por muralhas antigas. Com belas praias, arquitetura encantadora e uma cena de entretenimento crescente, a Croácia oferece um ambiente relaxante e culturalmente enriquecedor para nômades digitais.',
    },
    {
      id: 27,
      pais: 'Dinamarca',
      paisurl: 'dinamarca',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/copenhague.png`,
      fotocard: `${this.baseUrl}/card/copenhague.png`,
      cidade: 'Copenhague',
      custodevida: 'R$10.000 - R$15.000',
      temperatura: 'Média anual de 9°C',
      lingua: 'Dinamarquês',
      internet: '80 Mbps',
      descricao:
        'A Dinamarca é um país escandinavo conhecido por seu design, qualidade de vida e cenários encantadores. Copenhague, a capital, é uma cidade moderna com uma abordagem sustentável e cultural. Com uma forte infraestrutura, pistas para bicicletas e uma cena de café vibrante, a Dinamarca é um destino atraente para nômades digitais que buscam conforto e inspiração.',
    },
    {
      id: 28,
      pais: 'Finlândia',
      paisurl: 'finlandia',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/helsinque.png`,
      fotocard: `${this.baseUrl}/card/helsinque.png`,
      cidade: 'Helsinque',
      custodevida: 'R$7.500 - R$12.000',
      temperatura: 'Média anual de 6°C',
      lingua: 'Finlandês',
      internet: '60 Mbps',
      descricao:
        'A Finlândia é um país nórdico conhecido por sua educação de alta qualidade, natureza exuberante e design inovador. Helsinque, a capital, é uma cidade moderna que valoriza a qualidade de vida, com parques, saunas públicas e uma cena cultural diversificada. Com uma cultura única e oportunidades para apreciar a natureza, a Finlândia oferece um ambiente inspirador para nômades digitais.',
    },
    {
      id: 29,
      pais: 'Rússia',
      paisurl: 'russia',
      regiao: 'Europa e Ásia',
      tempovisa: '30 dias (e-Visa)',
      fotofull: `${this.baseUrl}/full/moscou.png`,
      fotocard: `${this.baseUrl}/card/moscou.png`,
      cidade: 'Moscou',
      custodevida: 'R$5.000 - R$9.000',
      temperatura: 'Média anual de 5°C',
      lingua: 'Russo',
      internet: '30 Mbps',
      descricao:
        'A Rússia é um país vasto, repleto de história, arte e arquitetura impressionantes. Moscou, a capital, é uma cidade imponente com a Praça Vermelha e o Kremlin como marcos icônicos. Com uma atmosfera única, uma cena cultural rica e a oportunidade de explorar locais históricos e culturais, a Rússia oferece uma experiência enriquecedora para nômades digitais.',
    },
    {
      id: 30,
      pais: 'Panamá',
      paisurl: 'panama',
      regiao: 'América Central',
      tempovisa: '6 meses',
      fotofull: `${this.baseUrl}/full/panama.png`,
      fotocard: `${this.baseUrl}/card/panama.png`,
      cidade: 'Cidade do Panamá',
      custodevida: 'R$3.500 - R$7.000',
      temperatura: 'Média anual de 27°C',
      lingua: 'Espanhol',
      internet: '20 Mbps',
      descricao:
        'O Panamá é um país que liga a América Central à América do Sul, conhecido pelo famoso Canal do Panamá e suas praias paradisíacas. A Cidade do Panamá, a capital, é uma cidade moderna com arranha-céus e uma mistura de culturas. Com uma economia em crescimento, natureza exuberante e oportunidades para explorar, o Panamá é um destino promissor para nômades digitais.',
    },
    {
      id: 31,
      pais: 'Islândia',
      paisurl: 'islandia',
      regiao: 'Europa',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/reiquiavique.png`,
      fotocard: `${this.baseUrl}/card/reiquiavique.png`,
      cidade: 'Reiquiavique',
      custodevida: 'R$9.000 - R$14.000',
      temperatura: 'Média anual de 5°C',
      lingua: 'Islandês',
      internet: '30 Mbps',
      descricao:
        'A Islândia é uma ilha vulcânica no Atlântico Norte, famosa por suas paisagens naturais únicas. Reiquiavique, a capital, oferece uma combinação de cultura local e modernidade. Com fontes termais, geleiras, auroras boreais e uma atmosfera única, a Islândia é um destino impressionante para nômades digitais em busca de aventuras.',
    },
    {
      id: 32,
      pais: 'Emirados Árabes Unidos',
      paisurl: 'emirados-arabes-unidos',
      regiao: 'Oriente Médio',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/dubai.png`,
      fotocard: `${this.baseUrl}/card/dubai.png`,
      cidade: 'Dubai',
      custodevida: 'R$10.000 - R$16.000',
      temperatura: 'Média anual de 26°C',
      lingua: 'Árabe',
      internet: '100 Mbps',
      descricao:
        'Os Emirados Árabes Unidos, com Dubai como uma de suas cidades mais famosas, é um centro financeiro e de negócios conhecido por sua arquitetura futurista e atrações de luxo. Dubai é uma cidade de contrastes, com arranha-céus imponentes, ilhas artificiais, shopping centers extravagantes e uma cena cosmopolita.',
    },
    {
      id: 33,
      pais: 'Hong Kong',
      paisurl: 'hong-kong',
      regiao: 'Ásia',
      tempovisa: '3 meses',
      fotofull: `${this.baseUrl}/full/hong-kong.png`,
      fotocard: `${this.baseUrl}/card/hong-kong.png`,
      cidade: 'Hong Kong',
      custodevida: 'R$8.000 - R$12.000',
      temperatura: 'Média anual de 23°C',
      lingua: 'Chinês (Cantonês) e Inglês',
      internet: '80 Mbps',
      descricao:
        'Hong Kong é uma metrópole dinâmica e um centro financeiro internacional, conhecido por sua arquitetura impressionante e diversidade cultural. A cidade oferece uma mistura de modernidade e tradição, com arranha-céus, mercados movimentados, e templos históricos lado a lado. Com uma das economias mais desenvolvidas da Ásia, uma vibrante cena gastronômica, e uma efervescente vida noturna, Hong Kong é uma opção empolgante para nômades digitais.',
    },
  ];

  getAllPais(): Pais[] {
    return this.PaisList;
  }

  getPaisByUrl(paisurl: string): Pais | undefined {
    return this.PaisList.find((Pais) => Pais.paisurl === paisurl);
  }
}
